Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CWsite.Models;
using Microsoft.AspNetCore.Http;

namespace CWsite.Controllers
{
    public class PlayersController : Controller
    {
        public IActionResult GetUser(string userName)
        {
            User u = new User();
            foreach (var user in RegistrationModel.Users)
            {
                if (user.Value._currentName == userName)
                {
                    u = user.Value;
                    break;
                }
            }
            if (HttpContext.Session.GetString("author") == u._login) return Redirect(nameof(Profile));
            HttpContext.Session.SetString("user", userName);
            return Redirect(nameof(Userpage));
        }

        public IActionResult Profile()
        {
            var name = new string(HttpContext.Session.GetString("author"));
            RegistrationModel.Users.TryGetValue(name, out var user);
            HttpContext.Session.SetString("user", user._currentName);
            return View();
        }

        public IActionResult Userpage()
        {
            return View();
        }

        public IActionResult GetClan(int clan)
        {
            if (clan == 1) HttpContext.Session.SetString("Clan", "Грозовое племя");
            if (clan == 2) HttpContext.Session.SetString("Clan", "Речное племя");
            if (clan == 3) HttpContext.Session.SetString("Clan", "Племя ветра");
            if (clan == 4) HttpContext.Session.SetString("Clan", "Племя теней");
            if (clan == 5) HttpContext.Session.SetString("Clan", "Звёздное племя");
            if (clan == 6) HttpContext.Session.SetString("Clan", "Одиночки/домашние");

            return Redirect(nameof(Clan));
        }

        public IActionResult Clan()
        {
            return View();
        }


    }
}

Views/Players/Clan.cshtml
@using Microsoft.AspNetCore.Http;

@{
    var clan = Context.Session.GetString("Clan");
    var thisClan = PlayersModel.GetClan(clan);
}

@{
    ViewData["Title"] = clan;
}


    <div>
        <h1>@clan</h1>


        @if (clan != "Одиночки/домашние")
        {
            <h2>Предводитель</h2>
            thisClan.TryGetValue("Предводитель", out var list);
            @if (list != null) foreach (var u in list)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Глашатай</h2>
            thisClan.TryGetValue("Глашатай", out var list2);
            @if (list2 != null) foreach (var u in list2)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Целитель(и)</h2>
            thisClan.TryGetValue("Целитель", out var list3);
            @if (list3 != null) foreach (var u in list3)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Ученик(и) целителя</h2>
            thisClan.TryGetValue("Ученик целителя", out var list4);
            @if (list4 != null) foreach (var u in list4)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Воители</h2>
            thisClan.TryGetValue("Воин", out var list5);
            @if (list5 != null) foreach (var u in list5)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Оруженосцы</h2>
            thisClan.TryGetValue("Оруженосец", out var list6);
            @if (list6 != null) foreach (var u in list6)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Старейшины</h2>
            thisClan.TryGetValue("Старейшина", out var list7);
            @if (list7 != null) foreach (var u in list7)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Котята</h2>
            thisClan.TryGetValue("Котёнок", out var list8);
            @if (list8 != null) foreach (var u in list8)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
        }
        else
        {
            <h2>Одиночки</h2>
            thisClan.TryGetValue("Одиночка", out var list);
            @if (list != null) foreach (var u in list)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
            <h2>Домашние</h2>
            thisClan.TryGetValue("Домашний", out var list2);
            @if (list2 != null) foreach (var u in list2)
                {
                    <p style="text-align: center">@Html.ActionLink(u._currentName, "GetUser", "Players", new { userName = u._currentName }, new { @class = "Link" }) </p>
                }
        }
    </div>

Views/Players/Profile.cshtml
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Профиль";
}

@{

    var log = Context.Session.GetString("author");
    RegistrationModel.Users.TryGetValue(log, out var user);
}

<div>
    <h1>Профиль</h1>
    <br />
    <span>Имя: @user._currentName</span> <br /><br />
    <span>Возраст: @user._age лун</span><br /><br />
    <span>Пол: @user._gender</span><br /><br />
    <span>Племя: @user._clan </span><br /><br />
    @if (user._rank != "Одиночка" && user._rank != "Домашний")
    {
    <span>Должность: @user._rank </span><br /><br />
    }
    <p>Описание: @user._description </p>

    <form style="margin: 0 25%;">
        <a class="Link" href="~/Home/Editing">Редактировать профиль</a>
        <br /><br />
        <a class="Link" href="~/Home/SignOut">Выйти</a>
        <br /><br />
    </form>
</div>

Views/Players/Userpage.cshtml
@using Microsoft.AspNetCore.Http;

@{
    var userName = Context.Session.GetString("user");
    var user = PlayersModel.GetUser(userName);
    var login = Context.Session.GetString("author");
}


@{
    ViewData["Title"] = userName;
}

<div>
    <h1>Профиль</h1>
    <br />
    <span>Имя: @user._currentName</span> <br /><br />
    <span>Возраст: @user._age лун</span><br /><br />
    <span>Пол: @user._gender</span><br /><br />
    <span>Племя: @user._clan </span><br /><br />
    @if (user._rank != "Одиночка" && user._rank != "Домашний")
    {
        <span>Должность: @user._rank </span><br /><br />
    }
    <p>Описание: @user._description </p>


    @if (login == "admin")
    {
        <a class="Link" href="~/Home/Editing">Редактировать профиль</a>
    }

</div>